image: node:latest

before_script:
  - yarn

stages:
  - deployExtension

deployExtension:
  stage: deployExtension
  tags:
    - master-pull
  only:
    - main
  script:
    - node --no-warnings ./deploy.js